steps:
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
#  secretEnv: ['USERNAME', 'PASSWORD']
#availableSecrets:
#  secretManager:
#  - versionName: projects/yougo-projects-labs/secrets/USERNAME/versions/1
#    env: 'PASSWORD'
#  - versionName: projects/yougo-projects-labs/secrets/PASSWORD/versions/1
#    env: 'USERNAME'
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  #args: ['-c', 'gcloud secrets versions access 1 --secret="databasepw"']
  args: ['-c', 'helm upgrade --install autobahn k8s/autobahn -f k8s/bots.yaml -n crawler --set rabbitpw=$$RABBITPW,rabbitMqHost=$$RABBITMQHOST,esApi=$$ESAPI,esCloudId=$$ESCLOUDID,esApiId=$$ESAPIID,imageTag=latest,dbpw=$$DATABASEPW']
  secretEnv: ['USERNAME', 'PASSWORD', 'ESAPI', 'ESCLOUDID', 'ESAPIID', 'DATABASEPW']
availableSecrets:
   secretManager:
   - versionName: projects/yougo-projects-labs/secrets/rabbitmq-password/versions/1
     env: 'USERNAME'
   - versionName: projects/yougo-projects-labs/secrets/rabbit-mq-host/versions/1
     env: 'PASSWORD'
timeout: 2400s
options:
  machineType: E2_HIGHCPU_32
